### ISSUE TITLE
Add helper methods for Java 11 in JavaVersion class

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/stf#44]
STF fails to detect Java version correctly on Java 11 

From JavaVersion.java: 
```
public boolean isJava11() throws StfException {
		return javaVersionOutput.startsWith("java version \"11");
	}
```
This doesn't match with the actual Java -version output. 

**java -version output from openjdk11:** 

```
openjdk version "11-adoptopenjdk" 2018-09-25
OpenJDK Runtime Environment (build 11-adoptopenjdk+23)
OpenJDK 64-Bit Server VM (build 11-adoptopenjdk+23, mixed mode)
```

**java -version output from openjdk11-openj9:** 

```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment (build 11+21)
Eclipse OpenJ9 VM (build master-b26c5e8c, JRE 11 Linux amd64-64-Bit Compressed References 20180718_10 (JIT enabled, AOT enabled)
OpenJ9   - b26c5e8c
OMR      - 8bbe28ce
JCL      - b44d19c4cb based on jdk-11+21)

```

Related error: 

```

18:45:20 GEN Classpath directories used by project 'openj9.test.sharedClasses.jvmti': 
18:45:20 GEN   /home/jenkins/workspace/Grinder/jvmtest/systemtest/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin
18:45:20 GEN   /home/jenkins/workspace/Grinder/jvmtest/systemtest/stf/stf.core/bin
18:45:20 GEN   /home/jenkins/workspace/Grinder/jvmtest/systemtest/stf/stf.load/bin
18:45:20 GEN   /home/jenkins/workspace/Grinder/jvmtest/systemtest/openj9-systemtest/openj9.stf.extensions/bin
18:45:20 GEN   /home/jenkins/workspace/Grinder/jvmtest/systemtest/openj9-systemtest/openj9.test.sharedClasses/bin
18:45:20 GEN   /home/jenkins/workspace/Grinder/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar
18:45:20 GEN   /home/jenkins/workspace/Grinder/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar
18:45:20 GEN   /home/jenkins/workspace/Grinder/jvmtest/systemtest/systemtest_prereqs/junit-4.12/junit-4.12.jar
18:45:20 GEN 22:45:20.172 - Using Mode NoOptions. Values = ''
18:45:20 GEN stderr Exception in thread "main" net.adoptopenjdk.stf.StfException: Unknown JVM release: linux_x86-64
18:45:20 GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.getJavaVersion(JavaVersion.java:225)
18:45:20 GEN stderr 	at net.adoptopenjdk.stf.environment.StfEnvironmentCore.getJavaVersion(StfEnvironmentCore.java:516)
18:45:20 GEN stderr 	at net.adoptopenjdk.stf.processes.definitions.JavaProcessDefinition.checkAndUpdateLevel(JavaProcessDefinition.java:896)
18:45:20 GEN stderr 	at net.adoptopenjdk.stf.processes.definitions.JavaProcessDefinition.addJvmOption(JavaProcessDefinition.java:167)
18:45:20 GEN stderr 	at net.openj9.stf.sharedClasses.StfSharedClassesExtension.runSharedClassesCacheCommand(StfSharedClassesExtension.java:77)
18:45:20 GEN stderr 	at net.openj9.stf.sharedClasses.StfSharedClassesExtension.doDestroyAllPersistentCaches(StfSharedClassesExtension.java:186)
18:45:20 GEN stderr 	at net.openj9.stf.SharedClassesAPI.setUp(SharedClassesAPI.java:119)
18:45:20 GEN stderr 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11-internal/Native Method)
18:45:20 GEN stderr 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11-internal/NativeMethodAccessorImpl.java:62)
18:45:20 GEN stderr 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11-internal/DelegatingMethodAccessorImpl.java:43)
18:45:20 GEN stderr 	at java.lang.reflect.Method.invoke(java.base@11-internal/Method.java:566)
18:45:20 GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.runStage(StfRunner.java:549)
18:45:20 GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.executeTest(StfRunner.java:293)
18:45:20 GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.main(StfRunner.java:69)
18:45:20 Generation failed

```
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/107/consoleFull

**Comment by Mesbah-Alam** [comment]
STF internally converts "openjdk version" to "java version" and then compares. This works for Java 11 only when we add a trim() at the end of the processed Java version String (unlike other Java versions). This must have to do with change in for version output in Java 11.
